services:
  minecraft:
    build: { dockerfile: ./docker/minecraft/Dockerfile, args: [ UID, GID ] }
    cap_drop: [ ALL ]
    tmpfs: [ /tmp:exec ]

    stop_grace_period: 2m
    stop_signal: 'SIGINT'

    tty: true
    stdin_open: true

    restart: 'unless-stopped'
    ports: [ '25565:25565/tcp' ]
    volumes: [ './data:/data:U', './logs:/server/logs:U' ]

    deploy: { resources: { limits: { cpus: "${CPUS:-2}", memory: "${MEMORY:-2G}" } } }
