name = "creative"
author = "amyavi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8bb9dab32b99a973b308cb4c5ccce0c6b199ea47b1a3b8865e36ccc985eaa66"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
