name = "creative"
author = "amyavi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c77ac2cc63863c64c811fe9a5abed8c8fae95d2111cac52c78765efbbb3ca3d2"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
